### PR TITLE
Step 6 - Reporting progress to chief

### PR DESCRIPTION
**Pull request by DarkChocLatte**
I am getting The Travis CI build failed on my commits and I'm trying to resolve the issue.

### CODE REVIEW

**Comment by jimmygoldshine** [comment]
Hi Jack,

Looking forward to starting the course!?

I was wondering if you could help me: How did you resolve this issue of the CI failure at Step 6? 

I'm having the same problems and I'm confident I've got the correct 4 suspects...

Any ideas would be great!
James

**Comment by DarkChocLatte** [comment]
I went through the whole course again. I'm not 100% sure but I believe that
I never merged the step-5 branch after switching back to the master branch.
I think this caused some issues for me, where I had to do a pull - fetch
request. When I followed the course correctly the second time I never had
to do a pull or fetch request.

I know it's sort of cheating deleting the repository and starting it all
again. But if you're really stuck that's what I would do.

**Comment by DarkChocLatte** [comment]
I went through the whole course again. I'm not 100% sure but I believe that
I never merged the step-5 branch after switching back to the master branch.
I think this caused some issues for me, where I had to do a pull - fetch
request. When I followed the course correctly the second time I never had
to do a pull or fetch request.

I know it's sort of cheating deleting the repository and starting it all
again. But if you're really stuck that's what I would do.

**Comment by DarkChocLatte** [comment]
This led to a CI build failure on all further steps 6-9.

**Pull request closed without merging**
