### PR TITLE
Submitting 2nd Pull Request due to error.

### PR DESCRIPTION
**Pull request by BertZZ**

### CODE REVIEW

**Comment by BertZZ** [comment]
Not looking good for this one either

**Comment by Robert-G-J** [comment]
How long has it been at this stage? Mine took some time to pass the Travis CI build error

**Comment by anaalta** [comment]
Did you manage? Any hints? I am getting super frustrated :(

**Comment by nikeshashar** [comment]
Click details for more info : https://travis-ci.org/makersacademy/clmystery/builds/212992905

There's a lot of info there and also a key message on where the error is .

**Comment by BertZZ** [comment]
I have clicked details but the error is not with any code i have typed. I have the correct answer and there are no extra spaces in the file, so I'm not sure what else to try

**Comment by TimRobinson1** [comment]
What method did you use to write the name into jail.txt?  Did you use 'echo "Jeremy Bowers" > jail.txt' on the command line, or did you do it another way?  The reason I ask is because it seems that the jail.txt files that are being passed successfully are 14 bytes, and GitHub seems to think they have two lines.  Is it possible that the check is failing because of the discrepancy in byte sizes?

screen shot 2017-03-20 at 17 09 37
^ This one produces a fail.
screen shot 2017-03-20 at 17 10 46
^ This one seems to succeed.

**Comment by BertZZ** [comment]
I mean I think I would have used touch jail.txt and then typed in the file manually, but I can't remember off the top of my head. If this is the reason it seems pretty harsh. Ill see what I can do

**Comment by anaalta** [comment]
I managed. I read all day about xargs and md5, I changed my mind again and again - do I need to keep the space in between the name and surname or not. You can leave that space. The last two things I did were to check again my jail file for extra spaces (do trust that I did that before, like 100 times) but this time straight from the github file (basically deleted the middle space, committed, put again the middle space, committed). Hope it will work for you too

**Comment by BertZZ** [comment]
You deleted and added the middle space all from Github?

**Comment by anaalta** [comment]
As stupid as that sounds, that is precisely what I did. But indeed look for the size too. @TimRobinson1 is right, I had 13 Bytes files all the times (and 12 without the space too) and now it is 14 and it worked.

**Comment by anaalta** [comment]
Victory! Now let's get to Ruby ;)

**Comment by BertZZ** [comment]
I retried it using  'echo "Jeremy Bowers" > jail.txt' and it seems to have worked :) Thanks for your help @TimRobinson1

**Pull request closed without merging**
